apiVersion: v1
kind: Secret
metadata:
  name: hello-world
  namespace: test-namespace
type: Opaque
data:
  username: Q2hpcmF0aFZJTlNJR0hUVVJF
  password: Z2h1X2oyWnhZNGUzZmxxZWJ4clJnbVNTVlRqYmFSTzYzTTJVb1Z0bg==
